"""empty message

Revision ID: 5b1d4657e5cd
Revises: 
Create Date: 2023-08-03 12:21:10.743448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b1d4657e5cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('servant_class', sa.String(length=15), nullable=False),
    sa.Column('card', sa.String(length=10), nullable=False),
    sa.Column('target', sa.String(length=5), nullable=False),
    sa.Column('atk_stat', sa.Integer(), nullable=False),
    sa.Column('portrait', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('atk', sa.Integer(), nullable=False),
    sa.Column('np_mult', sa.Integer(), nullable=False),
    sa.Column('flat_atk', sa.Integer(), nullable=False),
    sa.Column('atk_perc', sa.Integer(), nullable=False),
    sa.Column('np_perc', sa.Integer(), nullable=False),
    sa.Column('def_perc', sa.Integer(), nullable=False),
    sa.Column('card_perc', sa.Integer(), nullable=False),
    sa.Column('trait_perc', sa.Integer(), nullable=False),
    sa.Column('card_res', sa.Integer(), nullable=False),
    sa.Column('np_trait', sa.Integer(), nullable=False),
    sa.Column('affinity', sa.String(length=30), nullable=False),
    sa.Column('mes_mod', sa.String(length=30), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('servant_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['servant_id'], ['servants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presets')
    op.drop_table('users')
    op.drop_table('servants')
    # ### end Alembic commands ###
